### ISSUE TITLE
can't install plydata

### ISSUE THREAD

**Issue by zouhx11** [has2k1/plydata#12]
I'm sure I'm using python 3 on my mac. When I run command "pip install plydata", I get:

```
Exception:
Traceback (most recent call last):
  File "/Users/zouhx11/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/zouhx11/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/Users/zouhx11/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/Users/zouhx11/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/zouhx11/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/Users/zouhx11/anaconda3/lib/python3.6/site-packages/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/Users/zouhx11/anaconda3/lib/python3.6/email/feedparser.py", line 175, in feed
    self._input.push(data)
  File "/Users/zouhx11/anaconda3/lib/python3.6/email/feedparser.py", line 103, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'
```

**Comment by has2k1** [comment]
I got a chance to try installing plydata on a mac and I could not reproduce this bug.
